"use client";

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";

interface SvgPreviewProps {
  owner: string;
  repo: string;
}

export function SvgPreview({ owner, repo }: SvgPreviewProps) {
  const basePath = `/data`;

  return (
    <Card className="border-border bg-card">
      <CardHeader>
        <CardTitle className="text-base font-medium">README Preview</CardTitle>
        <CardDescription>
          Static SVGs generated by the GitHub Action.
        </CardDescription>
      </CardHeader>
      <CardContent className="flex flex-col gap-6">
        <div className="flex flex-col gap-2">
          <p className="font-mono text-xs tracking-wider text-muted-foreground uppercase">
            Star History
          </p>
          <div className="overflow-hidden rounded-lg border border-border bg-background">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={`${basePath}/star-history.svg`}
              alt={`Star history for ${owner}/${repo}`}
              className="h-auto w-full"
              onError={(e) => {
                (e.target as HTMLImageElement).style.display = "none";
              }}
            />
            <p className="p-4 text-center font-mono text-xs text-muted-foreground">
              Run the GitHub Action to generate star-history.svg
            </p>
          </div>
        </div>

        <Separator />

        <div className="flex flex-col gap-2">
          <p className="font-mono text-xs tracking-wider text-muted-foreground uppercase">
            Stargazer Wall
          </p>
          <div className="overflow-hidden rounded-lg border border-border bg-background">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={`${basePath}/stargazers-wall.svg`}
              alt={`Stargazer wall for ${owner}/${repo}`}
              className="h-auto w-full"
              onError={(e) => {
                (e.target as HTMLImageElement).style.display = "none";
              }}
            />
            <p className="p-4 text-center font-mono text-xs text-muted-foreground">
              Run the GitHub Action to generate stargazers-wall.svg
            </p>
          </div>
        </div>

        <pre className="overflow-x-auto rounded-lg border border-border bg-background p-4 font-mono text-xs text-muted-foreground">
{`<picture>
  <source media="(prefers-color-scheme: dark)" srcset="data/star-history.svg">
  <img alt="Star history" src="data/star-history.svg">
</picture>

![Stargazer wall](data/stargazers-wall.svg)`}
        </pre>
      </CardContent>
    </Card>
  );
}