"use client";

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";

interface SvgPreviewProps {
  owner: string;
  repo: string;
}

export function SvgPreview({ owner, repo }: SvgPreviewProps) {
  const basePath = `/data`;

  return (
    <Card className="border-white/8 bg-white/3 backdrop-blur-xl">
      <CardHeader>
        <CardTitle className="text-lg">README Preview</CardTitle>
        <CardDescription>
          Static SVGs generated by the GitHub Action — embed in your README.
        </CardDescription>
      </CardHeader>
      <CardContent className="flex flex-col gap-6">
        <div className="flex flex-col gap-2">
          <p className="text-sm font-medium text-muted-foreground">Star History</p>
          <div className="overflow-hidden rounded-xl border border-white/8 bg-zinc-950/50">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={`${basePath}/star-history.svg`}
              alt={`Star history for ${owner}/${repo}`}
              className="h-auto w-full"
              onError={(e) => {
                (e.target as HTMLImageElement).style.display = "none";
              }}
            />
            <p className="p-4 text-center text-xs text-muted-foreground">
              Run the GitHub Action to generate star-history.svg
            </p>
          </div>
        </div>

        <Separator className="bg-white/8" />

        <div className="flex flex-col gap-2">
          <p className="text-sm font-medium text-muted-foreground">Stargazer Wall</p>
          <div className="overflow-hidden rounded-xl border border-white/8 bg-zinc-950/50">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={`${basePath}/stargazers-wall.svg`}
              alt={`Stargazer wall for ${owner}/${repo}`}
              className="h-auto w-full"
              onError={(e) => {
                (e.target as HTMLImageElement).style.display = "none";
              }}
            />
            <p className="p-4 text-center text-xs text-muted-foreground">
              Run the GitHub Action to generate stargazers-wall.svg
            </p>
          </div>
        </div>

        <pre className="overflow-x-auto rounded-lg border border-white/8 bg-zinc-950/60 p-4 text-xs text-zinc-400">
{`<picture>
  <source media="(prefers-color-scheme: dark)" srcset="data/star-history.svg">
  <img alt="Star history" src="data/star-history.svg">
</picture>

![Stargazer wall](data/stargazers-wall.svg)`}
        </pre>
      </CardContent>
    </Card>
  );
}